# image: python:3.10

# stages:
#   - test

# before_script:
#   - pip install -r requirements.txt

# unit_tests:
#   stage: test
#   script:
#     - python generator/generate_framework.py --sql-root sql || true
#     - pytest -q || true
#   artifacts:
#     when: always
#     paths:
#       - tests
#       - test_config
#       - .pytest_cache
